---
# template details
blank_template_store_path: "templates"
built_template_store_path: "files"
base_template_name:        "ec_TEMPLATE_new.yml"

# device infomation
ec_device_name:         "test-ec-vm"
rendered_template_name: "{{  built_template_store_path  }}/{{  ec_device_name  }}.yaml"

# unity Orchestrator details
orchip:   "18.217.100.212" 
ztc_name: "{{  ec_device_name }}.yaml"
auto_apply: false

# Template vars
#############################
# Appliance infomation
host_name:      "{{  ec_device_name | lower  }}"
group_name:     "Group 1"
site_name:      "site 1"
network_role:   "non-hub"
region_name:    ""
address_1:      "31 Fishburn Road"
address_2:      ""
city_name:      "San Jose"
state_name:     "California"
zip_code:       "94088"
country_name:   "US"
contact_name:   "sjcc.edu"
contact_email:  "school@sjcc.edu"
contact_number: "(408) 298-2181"

#############################
lan_interfaces:
  - interface: "lan0.600"
    interface_label: "TRUST"
    interface_type: "lan"
    interface_comment: "Main lan interface"
    ip_address: "10.29.55.245/28"
    next_hop: "10.29.55.241"
    zone: ""
  - interface: "lan0.34"
    interface_label: "GUEST_WIRELESS"
    interface_type: "lan"
    interface_comment: "lan guest-wireless interface"
    ip_address: "198.168.34.1/24"
    next_hop: ""
    zone: ""

#############################
wan_interfaces:
  - interface: "wan0"
    interface_label: "INET1"
    interface_type: "wan"
    interface_comment: "ISP 1 wan interface"
    ip_address: "198.168.0.2/24"
    next_hop: "198.168.0.3"
    ob_max_bw: "200000"
    ib_max_bw: "200000"
    firewall_mode: "statefulSNAT"
    behind_nat: "auto"
    zone: ""
  - interface: "wan1"
    interface_label: "INET2"
    interface_type: "wan"
    interface_comment: "ISP 1 wan interface"
    ip_address: "198.168.10.2/24"
    next_hop: "198.168.10.3"
    ob_max_bw: "200000"
    ib_max_bw: "200000"
    firewall_mode: "statefulSNAT"
    behind_nat: "auto"
    zone: ""

#############################
template_groups:
  - group: "ec_physical"
  - group: "ec_vm"
 
#############################
business_intent_overlays:
  - bio: "RealTime"
  - bio: "CriticalApps"
  - bio: "BulkApps"
  - bio: "DefaultOverlay" 


 
