---
# tasks file for push_to_orchestrator
    
    - name: "Login to the orchestrator"
      uri:
        validate_certs: no
        url:  "https://{{ orchip }}/gms/rest/authentication/login"
        body: {"user": "{{ orch_user }}", "password": "{{ orch_password }}"}
        body_format: json
        return_content: yes
        method: POST
        headers:
          Content-Type: "application/json"
      register: orch 
      
    - name: "Post the file to the orchestrator"
      uri:
        validate_certs: no
        url:  "https://{{ orchip }}/gms/rest/gms/appliance/preconfiguration/"
        body: {"name": "{{ ztc_name }}", "serialNum": "{{ ec_serial }}", "configData": "{{ preconfigb64.stdout }}", "comment": "{{ ztc_comment }}", "autoApply": "{{ auto_apply }}"}
        body_format: json
        return_content: yes
        method: POST
        headers:
          Content-Type: "application/json"
          Cookie: "{{ orch.set_cookie }}"
