---
- name: Create a Silver Peak Preconfiguration File 
  hosts: localhost
  gather_facts: false

  vars:
    orchip: seteam-orchestrator.silverpeak.cloud 
    filename: ec.yml 
    ztc_name: craigtest
    city_name: "Broadlands"
    auto_apply: true

  vars_files: 
    #- /home/craig/buildyaml/sewan.yml

  tasks:
    - name: import variable
      include_vars: 
        file: "{{ filename }}"  
        name: preconfig
        
    - name: "Create preconfig template"
      template:
       src: "{{ filename }}"
       dest: "ec_new.yaml"
      tags:
       "create_template"     

    - name: do encode
      shell: echo {{ preconfig | to_yaml | b64encode }}  
      register: preconfigb64

    - name: Login
      uri:
        validate_certs: no
        url:  "https://{{ orchip }}/gms/rest/authentication/login"
        body: {"user": "{{ sewan_user }}", "password": "{{ sewan_password }}"}
        body_format: json
        return_content: yes
        method: POST
        headers:
          Content-Type: "application/json"
      register: orch 
      
    - name: Post File 
      uri:
        validate_certs: no
        url:  "https://{{ orchip }}/gms/rest/gms/appliance/preconfiguration/"
        body: {"name": "{{ ztc_name }}", "configData": "{{ preconfigb64.stdout }}", "autoApply": "{{ auto_apply }}"}
        body_format: json
        return_content: yes
        method: POST
        headers:
          Content-Type: "application/json"
          Cookie: "{{ orch.set_cookie }}"
 

